# Generated by Django 4.2.9 on 2024-02-28 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flujos', '0002_repartidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='fechaVcto',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='entregas',
            name='localDestino',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='entregas',
            name='reponedor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='fechaEntrega',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='producto',
            field=models.CharField(default='', max_length=50),
        ),
    ]
